### Server Port ###
server:
  port: 8080

### MySQL ###
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url, username, password는 환경변수로 주입

  ### JPA ###
  jpa:
    hibernate:
      ddl-auto: none    # 프로덕션에서는 none 또는 validate 사용
    show-sql: false     # 프로덕션에서는 비활성화
    properties:
      hibernate:
        format_sql: false

  ### Resource Server ###
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}  # 환경변수로 주입
    cors:
      allowed-origins: ${ALLOWED_ORIGINS} # 환경변수로 주입

  ### Multipart File Upload Configuration ###
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

### AWS S3 Configuration ###
aws:
  s3:
    # accesskey, secretkey는 환경변수로 주입
    bucket: epari-prod  # 또는 환경변수로 주입
    region: ap-northeast-2

### AWS SDK Logging Configuration ###
logging:
  level:
    root: INFO
    com:
      example:
        epari: INFO
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
    software:
      amazon:
        awssdk: WARN
    org:
      hibernate: INFO

### File Upload Directory Configuration ###
file:
  upload:
    lecture-content: lecture-content
    assignment: assignment
    submission: submission
    question: questionnotices
    answer: answer
    notice: notice
    path: /app/uploads  # 컨테이너 내부 경로
